unit SapiCon;

interface

const
 cmCopyr    =1000;
 cmLoad     =1001;
 cmSave     =1002;
 cmNew      =1003;
 cmInfo     =1004;
 cmEditLine =1005;
 cmEdit     =1006;
 cmFind     =1008;
 cmAgain    =1009;
 cmSLine    =1010;
 cmRun      =1011;
 cmStep     =1012;
 cmReset    =1013;
 cmEval     =1014;
 cmModify   =1015;
 cmTerminal =1016;
 cmFillAnal =1017;
 cmClrScr   =1018;
 cmToSapi   =1019;
 cmFromSapi =1020;
 cmConfig   =1021;
 cmNewLine  =1022;
 cmBreakP   =1023;
 cmDelLine  =1024;
 cmCompute  =1025;
implementation

end.